---
title             : "My Title Goes Here"
shorttitle        : "My short title goes here"

author: 
  - name: Jeffrey N. Rouder
    affiliation: "1"
    corresponding: yes    # Define only one corresponding author
    email: jrouder@uci.edu
    address: Department of Cognitive Science, University of California, Irvine, CA, 92697
  - name: Martin Schnuerch
    affiliation: "2"
  - name: Julia M. Haaf
    affiliation: "3"
  - name: Richard D. Morey 
    affiliation: "4"


affiliation       :
  - id: 1
    institution: University of California, Irvine
  - id: 2
    institution: University of Mannheim
  - id: 3
    institution: University of Amsterdam
  - id: 4
    institution: University of Cardiff


author_note       : "This paper was written as part of an open science class"

abstract          : >
  "Here"
  
keywords          : "are just words"

bibliography      : ["lab.bib"]
figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no


class             : "man"
header-includes:
   - \usepackage{bm}
   - \usepackage{amsmath}
   - \usepackage{setspace}
output            : papaja::apa6_pdf
---

```{r include=FALSE}
library(lme4)
library(lmerTest)
library(tidyverse)
```

You can just start typing your intro. 

# Method

blah blah

# Results

```{r loadData}
dat=read.csv(url('https://raw.githubusercontent.com/PerceptionCognitionLab/data3/master/brightCompare1/data'),header=TRUE)
```

```{r acc}
m=tapply(dat$correct,list(dat$targLevel,dat$backLevel),mean)
```

```{r wrangling, include=FALSE}
dat <- dat %>%
  mutate(condition = targLevel*backLevel)

moddat <- dat %>%
  group_by(pid, condition) %>%
  mutate(perf = mean(correct)) %>%
  distinct(pid, condition, .keep_all = TRUE) %>%
  arrange(pid, condition)
moddat$condition <- as.factor(moddat$condition)
```


```{r analysis}
mod0 <- lmer(correct ~ condition + (1 | pid), data = dat)
mod <- lmer(correct ~ condition + (1 + condition | pid), data = dat)
anova(mod0, mod, refit = FALSE)
```

```{r}
ggplot(data = moddat, mapping = aes(x = condition, y = perf)) +
  geom_point() +
  geom_smooth(aes(group = pid), method = "lm", se = FALSE, color = "steelblue") +
  theme_bw()

plot(moddat$condition, moddat$perf, type="n",
     xlab="Congruency", ylab="Performance")
L2units <- rownames(coef(mod)$pid)

for ( i in 1:length(L2units) ) {
  curve(coef(mod)$pid[i,1] + coef(mod)$pid[i,2] * x,  
        lwd=1, col=1, add=TRUE)
}
#points(moddat$condition, moddat$perf)
```


```{r res,fig.cap="My Results"}
matplot(1:2,m,typ='l',axes=F,xlab="Stimulus",ylab="Accuracy",
        lty=1,ylim=c(0,1),lwd=2)
axis(1,at=1:2,lab=c("Darker Left","Darker Right"))
axis(2)
```

The overall accuracy was `r round(mean(m),2)`.  Figure \ref{fig:res} blah blah.

# Discussion

